# HGGdic doesn't have all HGG seq name, need help of LGGdic.
### LGG only: 506 different name, GBM: 793 different name
### LGG + GBM 1187 different name: (506 + 793)- 1187 = 112 overlap

# line 7: LGGdic, line 518: HGGdic

LGGdic = {
    't1_tir_cor'        : 'T1cor'     ,
    'dti for nsurg'     : 'DTI'       ,
    'dti for nsurg_FA'  : 'DTI'       ,
    'localizer'         : 'localizer' ,
    't1_tir_AX'         : 'T1ax'      ,
    'dti for nsurg_TRACEW': 'DTI'     ,
    'dti for nsurg_ADC' : 'DTI'       ,
    'VOLUMETRIC AXIAL'  : '3dT1ax'    ,
    't1_tir_SAG'        : 'T1sag'     ,
    'FLAIR AX'          : 'FLax'      ,
    'AX T1_IR_TSE_5mm'  : 'T1ax'      ,
    'PERF FE_EPI 20 TE' : 'Perf'      ,
    'facFA COLOR'       : 'FAcolormap',
    'faFA'              : 'FA'        ,
    'Pre AX T1W_IR_TSE' : 'T1ax'      ,
    'POST_T1W_3D_TFE'   : '3dCET1'    ,
    '+cor t1 1mm'       : '3dCET1cor' ,
    'dADC'              : 'ADC'       ,
    'SAG T1W_IR_TSE'    : 'T1sag'     ,
    'Post AX T1W_IR_TSE': 'CET1ax'    ,
    'Survey'            : 'localizer' ,
    'AX T2W_DRIVE'      : 'T2ax'      ,
    'AX T2 1MM'         : '3dT2ax'    ,
    'DTI_32 direction'  : 'DTI'       ,
    'COR T2 1MM'        : '3dT2cor'   ,
    'isoB 1000 I'       : 'DWI'       ,
    'Reg - DTI_high_iso SENSE': 'DTI' ,
    'FLAIR_LongTR'      : 'FL'        ,
    '3D_Brain_View_T2_SHC': '3dT2ax'  ,
    '+ax t1 1mm'        : '3dCET1ax'  ,
    'FLAIR AXIALS'      : 'FLax'      ,
    'T2 AXIALS'         : 'T2ax'      ,
    'MP RAGE AXIAL'     : '3dT1ax'    ,
    'DTI DIFF'          : 'DTI'       ,
    'SCOUT'             : 'localizer' ,
    'AXIAL GRE'         : 'T2starax'  ,
    'AXIAL T1 PRE GD'   : 'CET1ax'    ,
    'SAG LOCAL'         : 'localizer' ,
    'AXIAL  FSE'        : 'NoName'    ,
    'AXIAL T1 SI LOCALIZER': 'Localizer',
    'NEW AXIAL PERFUSION/20S DELAY': 'Perf',
    'AXIAL T1 POST GD'  : 'CET1ax'    ,
    'AXIAL DIFFUSION'   : 'DWIax'     ,
    'AXIAL FLAIR'       : 'FLax'      ,
    'AX T1 POST GD FLAIR': 'CET1ax'   ,
    'DTI 2.6mm WH'      : 'DTI'       ,
    'COR  T1 POST GD FLAIR': 'CET1cor',
    'SAG T1 (FLAIR)'    : 'T1sag'     ,
    '3 PLANE LOC'       : 'localizer' ,
    'AX T2 FR-FSE RF2 150': 'T2ax'    ,
    'AXIAL PERFUSION'   : 'Perf'      ,
    'ASSET cal'         : 'localizer' ,
    'AX T1 pre gd'      : 'T1ax'      ,
    'FLAIR SAG'         : 'FLsag'     ,
    'T2 COR'            : 'T2cor'     ,
    'FLAIR COR'         : 'FLcor'     ,
    'T2 SAG'            : 'T2sag'     ,
    'T2 AX'             : 'T2ax'      ,
    'T2-weighted trace' : 'DWIT2wtrace',
    'Fractional Ansio'  : 'FA'        ,
    'AXIAL DTI'         : 'DTI'       ,
    'AXIAL FSE'         : 'NoName'    ,
    'COR T1 POST GD'    : 'CET1cor'   ,
    'Ax T1 2.5mm for surgery': 'NoName',
    'AXIAL T1'          : 'T1ax'      ,
    'Ax FLAIR 2.5mm for surgery': 'FLAIRthinax',
    'Average DC'        : 'ADC'       ,
    'SAG T1'            : 'T1sag'     ,
    'DTI 2.6mm WH  COVERED CUT AIR': 'DTI',
    'DTI ASSET'         : 'DTI'       ,
    'AXIAL T1 POST GD FOR SPECT.': 'CET1ax',
    'AXIAL T1 PRE-GAD/SAME LOCS': 'T1ax',
    'AXIAL T1 LOC FOR SPECT 1-4 SL': 'localizer',
    'AXIAL GR ECHO/CHANGE AUTOLOCK': 'NoName',
    '+ C COR T1 SE F'   : 'CET1cor'   ,
    '+ C Sag T1 SE F'   : 'CET1sag'   ,
    'AX 3D SPGR'        : '3dCET1ax'  ,
    'Calibration'       : 'calibration',
    '+ C AX 3D SPGR'    : '3dCET1ax'  ,
    '3-pl T2* FGRE S'   : 'localizer' ,
    'T2 AX TSE BRAIN'   : 'T2ax'      ,
    'T2_tse3d_SAG'      : '3dT2sag'   ,
    'T1 MPRAGE AX POST STEALTH': '3dT1ax',
    'cow mip head to foot': 'MIP'     ,
    'relCBF'            : 'rCBF'      ,
    'ep2d_diff_3scan_trace_p2_ADC': 'DWI',
    'FLAIR_AX_BLADE'    : 'FLax'      ,
    'EPI T2 STAR'       : 'T2starax'  ,
    'T1_SAG_TSE_FC(READ)': 'T1sag'    ,
    'Perfusion_Weighted': 'Perf'      ,
    'TOF_3D_multi-slab' : 'TOF'       ,
    'T1_SAG_SE'         : 'T1sag'     ,
    'T1_AX_SE'          : 'T1ax'      ,
    'cow mip left to right': 'MIP'    ,
    't2_blade_AX_320 FS': 'T2ax'      ,
    'T1_COR_SE_FLOWCOMP': 'T1cor'     ,
    'ep2d_diff_3scan_trace_p2': 'DWI' ,
    'T1_AX_SE_FLOWCOMP' : 'T1ax'      ,
    'T1_AX_MPR_SEL_3D'  : '3dT1ax'    ,
    'T1_SAG'            : 'T1sag'     ,
    'ep2d_perf_tra_RELCBV': 'rCBV'    ,
    'ep2d_diff_3scan_trace': 'DWI'    ,
    'ep2d_perf_tra_RELMTT': 'MTT'     ,
    'ep2d_diff_3scan_trace_ADC': 'DWI',
    'ep2d_perf_tra_RELCBF': 'rCBF'    ,
    'ep2d_perf_tra_TTP' : 'TTP'       ,
    'T2_AX_TSE_3MM FS'  : 'T2fsax'    ,
    'ep2d_perf_p3_RELCBV': 'rCBV'     ,
    'TTP_ep2d_perf_p3'  : 'TTP'       ,
    't1_fl2d_sag'       : 'T1sag'     ,
    't1_fl2d_cor'       : 'T1cor'     ,
    'ep2d_perf_p3_RELMTT': 'MTT'      ,
    't2_tse_tra_384_3mm fs': 'T2ax'   ,
    't1_mprage_tra_p2_iso_1.0': '3dT1ax',
    't2_tirm_tra_dark-fluid': 'FLax'  ,
    'ep2d_perf_p3_RELCBF': 'rCBF'     ,
    'ep2d_perf_p3_TTP'  : 'TTP'       ,
    'Ax T1 MP SPGR + C' : '3dCET1'    ,
    'COR T1 SE + C'     : 'CET1cor'   ,
    'Ax T2 FSE INTER'   : 'T2ax'      ,
    '3-P,Localizer'     : 'localizer' ,
    'SAG T1 SE + C'     : 'CET1sag'   ,
    '3D MOTSA sense'    : 'NoName'    ,
    'COW'               : 'NoName'    ,
    'POSTERIOR'         : 'NoName'    ,
    'FFE FOR BLEED'     : 'T2starax'  ,
    'dADC MAP'          : 'ADC'       ,
    'eBo'               : 'NoName'    ,
    'eB1000i'           : 'DWI'       ,
    'T1 AX  SE'         : 'T1ax'      ,
    'T1 COR SE'         : 'T1cor'     ,
    'T2 AX FLAIR'       : 'FLax'      ,
    'PDW_TSE'           : 'PDax'      ,
    'T1W _ SE'          : 'T1'        ,
    'T1 AX SE'          : 'T1ax'      ,
    'T2W_TSE'           : 'T2'        ,
    'RT  COW'           : 'NoName'    ,
    'T1 SAG SE'         : 'T1sag'     ,
    'LT COW'            : 'NoName'    ,
    '3D DCE DYNAMIC (PERF)': 'DCE'    ,
    '3D DCE T1 MAPPING X 5': 'T1map'  ,
    'AX 3D SPGR+C'      : '3dCET1'    ,
    'Ax DW DW-EPI S b=1000,T2': 'DWI' ,
    'COR GRE T2'        : 'T2starcor' ,
    'COR T1+C'          : 'CET1cor'   ,
    'SAG T1+C'          : 'CET1sag'   ,
    'Ax Flair irFSE H'  : 'FLax'      ,
    'Apparent Diffusion Coefficient (m??/s)': 'ADC',
    'Ax T2 FSE H'       : 'T2ax'      ,
    'Exponential Apparent Diffusion Coefficient': 'expADC',
    '3D DCE T1 MAP'     : 'T1map'     ,
    '(OPT) AX T2 FSE inter': 'T2ax'   ,
    'TENSOR ASSET'      : 'DTI'       ,
    'dti for nsurg_ColFA': 'DTI'      ,
    'AX 3D SPGR PRE GAD': '3dCET1ax'  ,
    '+C COR T1 SE F'    : 'CET1cor'   ,
    '+C Sag T1 SE F'    : 'CET1sag'   ,
    '3 pl T2* FGRE S'   : 'localizer' ,
    'AX 3D SPGR +GAD'   : '3dCET1ax'  ,
    'ep2d_diff_mddw_20_p2 wip': 'DTI' ,
    'ep2d_diff_mddw_20_p2 wip_FA': 'DTI',
    'MPR SAG Post'      : 'MPRCET1sag',
    'MPR COR Post'      : 'MPRCET1cor',
    'MPR COR'           : 'NoName'    ,
    'ep2d_diff_mddw_20_p2 wip_ColFA': 'DTI',
    'T2 axial'          : 'T2ax'      ,
    'MPR SAG'           : 'NoName'    ,
    'ep2d_diff_mddw_20_p2 wip_ADC': 'ADC',
    'ep2d_diff_mddw_20_p2 wip_TRACEW': 'DTI',
    't1_mprage_tra Gd'  : '3dCET1ax'  ,
    'FLAIR axial'       : 'FLax'      ,
    't1_mprage_tra'     : '3dT1ax'    ,
    'SPEC'              : 'NoName'    ,
    'ax per'            : 'Perf'      ,
    'AXIAL T1 PRE/POST GD': 'NoName'  ,
    'AX DIFF'           : 'DWI'       ,
    'SAG LOC'           : 'localizer' ,
    'axial si local'    : 'NoName'    ,
    'axial gre'         : 'NoName'    ,
    'Ax T1 FS BRAIN POST': 'CET1fsax' ,
    'Ax T1'             : 'T1ax'      ,
    'AX FLAIR'          : 'FLax'      ,
    'SAG T1 POST'       : 'CET1sag'   ,
    '3 Plane Localizer' : 'localizer' ,
    'AX GRE FOR SUSCEPTIBILITY': 'T2star',
    'AX FSE T2'         : 'T2ax'      ,
    'Apparent Diffusion Coefficient (mm?/s)': 'ADC',
    'SAG T1 LOC'        : 'localizer' ,
    'COR T1 POST GAD'   : 'CET1cor'   ,
    'AX DIFFUSION'      : 'DWI'       ,
    'COR T1 SE F'       : 'T1cor'     ,
    '(OPTIONAL) AX FSE T2 inter ': 'T2ax',
    'Sag T1 SE F+C'     : 'CET1sag'   ,
    'PROP ADC'          : 'ADC'       ,
    'PROP COMB'         : 'NoName'    ,
    'PROP eADC'         : 'ADC'       ,
    '8hrbrain,Ob,2D,DWIProp': 'DWI'   ,
    'Prop T2 TRF'       : 'T2ax'      ,
    'AX T2 FSE inter'   : 'T2ax'      ,
    'POST COR T1  3MM'  : 'CET1ax'    ,
    'POST AX T1 BRAIN LAB 1MM': '3dCET1ax',
    'AX T1W_IR_TSE'     : 'T1ax'      ,
    'Survey (NO PAD)'   : 'localizer' ,
    'POST AX T1  3MM'   : 'CET1ax'    ,
    'POST SAG T1 3d'    : '3dCET1sag' ,
    'axial t1/gd'       : 'CET1ax'    ,
    'axial perfusion'   : 'Perf'      ,
    'axial mpgr'        : '3dT2starax',
    'spectro t1 localizer': 'localizer',
    'axial diffusion'   : 'DWI'       ,
    'axial t1 pre gd'   : 'T1ax'      ,
    '(OPTIONAL)Ax T2 FSE INTER': 'T2ax',
    'Ax T1 MP SPGR'     : '3dT1ax'    ,
    'loc'               : 'localizer' ,
    'FGAITR SAG'        : 'NoName'    ,
    'T2-W 3D FLAIR'     : '3dFL'      ,
    'T1-w 3D FGATIR-WIP sel IR': '3dT1',
    'FGAITR AX'         : 'NoName'    ,
    'FGAITR COR'        : 'NoName'    ,
    'Surface DC'        : 'ADC'       ,
    'Magnitude DC'      : 'ADC'       ,
    'Relative Aniso.'   : 'FA'        ,
    'Dxz diffusion coefficient': 'ADC',
    'Dyy diffusion coefficient': 'ADC',
    'Dyz diffusion coefficient': 'ADC',
    'Diffusion Tensor 25': 'DTI'      ,
    'Fractional Aniso.' : 'FA'        ,
    'Maximum eigenvalue': 'Eigenvalue',
    'AX PD FSE-IR RF2 130': 'PDax'    ,
    'Dxy diffusion coefficient': 'ADC',
    'Middle eigenvalue' : 'Eigenvalue',
    'AXIAL FLAIR RF2  150': 'FLax '   ,
    'Volume / Average Aniso.': 'FA'   ,
    'AX T1 LOC'         : 'localizer' ,
    'Dzz diffusion coefficient': 'ADC',
    'Anisotropy index'  : 'FA'        ,
    'Volume / Surface Aniso.': 'FA'   ,
    'AX T1 LOC  PODT GD': 'localizer' ,
    'Surface / Average Aniso.': 'FA'  ,
    'Minimum eigenvalue': 'eigenvalue',
    'Volume DC'         : 'ADC'       ,
    'Exponential attenuation': 'ADC'  ,
    'Isotropic image'   : 'DWI'       ,
    'Dxx diffusion coefficient': 'ADC',
    'Volume ratio Aniso.': 'ADC'      ,
    'AXIAL T2'          : 'T2ax'      ,
    '*AX 3D FOR STRYKER PROTOCOL': 'localizer',
    'AXIAL T1 POST GAD FATSAT': '3dCET1fsax',
    'SAG T1 POST GAD'   : 'CET1sag'   ,
    'MPR AX'            : 'NoName'    ,
    't2_spc_ns_sag_dark-fl_p2_iso': '3dFLsag',
    'MP RAGE AXIAL REPEAT': '3dT1ax'  ,
    '+C SAG T1 SE'      : 'CET1sag'   ,
    '+C COR T1 SE'      : 'CET1cor'   ,
    'mpRAGE AX,3D,SPGR,Fast': '3dT1ax',
    'Average DC2500'    : 'ADC'       ,
    'EPI DWI ASSET'     : 'DWI'       ,
    'DKI ASSET 2500'    : 'DKI'       ,
    'mpRAGE Sag,3D,SPGR,Fast': '3dT1sag',
    'AX T1'             : 'T1ax'      ,
    'AX 3D SPGR + C'    : '3dCET1'    ,
    'SAG MPR ISO1MM'    : 'MPRsag'    ,
    'COR MPR ISO1MM'    : 'MPRcor'    ,
    'DIFFUSION'         : 'DWI'       ,
    'T1W_3D_STRYKER'    : '3dT1'      ,
    'AXIAL  T2'         : 'T2ax'      ,
    'SAG T1 SE'         : 'T1sag'     ,
    ' Ax T2 Flair '     : 'FLax'      ,
    'BRAIN_STRYKER/NEW_DIFF': 'DWI'   ,
    'BRAIN_STRYKER/FLAIR': 'FL'       ,
    'BRAIN_STRYKER/T1_CORONAL': 'T1cor',
    'BRAIN_STRYKER/T1_SAG': 'T1sag'   ,
    'BRAIN_STRYKER/T1_AXIAL': 'T1ax'  ,
    'BRAIN_STRYKER/AX-RAGE-STRY': '3dT1ax',
    'BRAIN_STRYKER/T2_AX_DOUBLE': 'T2ax',
    'BRAIN_STRYKER/scout': 'localizer',
    'BRAIN_STRYKER/t1_AX': 'T1ax'     ,
    'DIFFUSION_ADC'      : 'DWI'      ,
    'T1 COR'             : 'T1cor'    ,
    't2_spc_ns_AXp2_da-fl_iso': '3dT2ac',
    'T1 SAG'             : 'T1sag'    ,
    'sag t1'             : 'T1sag'    ,
    'axial perf.'        : 'Perf'     ,
    'axial t1 post gd'   : 'CET1ax'   ,
    'axial diff.'        : 'DWI'      ,
    'DWI ASSET'          : 'DWI'      ,
    'Sag T2 FSE'         : 'T2sag'    ,
    'Cor 2D T2*GRE'      : 'T2starcor',
    'AXIAL T2 FLAIR'     : 'FLax'     ,
    '+C Ax T1 MP SPGR'   : '3dCET1ax' ,
    'T1 COR Gd'          : 'CET1cor'  ,
    'TIR T1 AX'          : 'T1ax'     ,
    'T1 SAG Gd'          : 'CET1sag'  ,
    'T1 AXIAL Gd'        : 'CET1ax'   ,
    'MRHG T2 AXIALS'     : 'T2ax'     ,
    'MP RAGE AXIAL PG'   : '3dT1ax'   ,
    't2_spc_tra_p2_384'  : '3dT2ax'   ,
    'STRYKER'            : 'NoName'   ,
    'RT   MRA'           : 'MRA'      ,
    'eB1000I'            : 'DWI'      ,
    '3D MC  MRA'         : 'MRA'      ,
    'T1 COR POST'        : 'CET1cor'  ,
    'T2W_FFE bleed'      : 'T2starax' ,
    'MRA'                : 'MRA'      ,
    'T1 SE PRE'          : 'T1ax'     ,
    'T1 SAG POST'        : 'CET1sag'  ,
    'AX PD'              : 'PDax'     ,
    'T1 SE POST'         : 'CET1ax'   ,
    'eB 0'               : 'DWIb0'    ,
    'Reg - DIFFUSION SENSE': 'DWI'    ,
    'LT   MRA'           : 'MRA'      ,
    'Survey_MST'         : 'localizer',
    'dadc'               : 'ADC'      ,
    'T2-WHOLE BRAIN'     : 'T2ax'     ,
    'THINS'              : 'NoNmae'   ,
    'Surview'            : 'NoName'   ,
    'CAP5'               : 'NoNmae'   ,
    'HR'                 : 'NoNmae'   ,
    'POST AX 3D SPGR'    : '3dCET1ax' ,
    'Prop DWI '          : 'DWI'      ,
    'PROBE 3D CSI'       : 'NoName'   ,
    'AXIAL T1 GD'        : 'CET1ax'   ,
    'Reg - DTI_low SENSE': 'DTI'      ,
    'AX T1 FLAIR PRE'    : 'T1ax'     ,
    'AX T2 FLAIR'        : 'FLax'     ,
    'POST AX T1 FLAIR'   : 'CET1ax'   ,
    'dADC ISO'           : 'ADC'      ,
    'POST COR T1'        : 'CET1cor'  ,
    'isoDWI ISO'         : 'DWI'      ,
    'AX T2'              : 'T2ax'     ,
    'DTI_low'            : 'DTI'      ,
    'Sag T1 SE F'        : 'T1sag'    ,
    'BRAIN_CONTRAST/NEW_DIFF': 'NoName',
    'BRAIN_CONTRAST/T1_AXIAL_C+': 'CET1ax',
    'BRAIN_CONTRAST/DOUBLE_ECHO': 'doubleax',
    'BRAIN_CONTRAST/T1_SAGITTAL': 'T1sag',
    'BRAIN_CONTRAST/hemosiderin': 'T2star',
    'MIPSeries0004'      : 'MIP'      ,
    'MIPSeries0003'      : 'MIP'      ,
    'BRAIN_MRA_MRV/MOTSA-3-SLAB': 'MRA',
    'BRAIN_CONTRAST/T1_CORONAL_': 'CET1cor',
    'BRAIN_MRA_MRV/2D_TOF_CORON': 'MRA',
    'BRAIN_CONTRAST/FLAIR': 'FL'      ,
    'BRAIN_CONTRAST/SCOUT': 'localizer',
    'BRAIN_CONTRAST/T1_AXIAL': 'T1ax' ,
    'COR C+'             : 'CET1cor'  ,
    '+AX T1'             : 'CET1ax'   ,
    'AX PD/T2'           : 'doubleax' ,
    'DIFF 1000 24 FOV'   : 'DWI'      ,
    '3 PLANE'            : 'localizer',
    'Ax T1 MP SPGR PRE GAD': '3dT1ax' ,
    'COR T1 SE+C'        : 'CET1cor'  ,
    'Ax T2 FSE'          : 'T2ax'     ,
    'Ax T1 MP SPGR + GAD': '3dCET1ax' ,
    '2D EPI DWI ASSET'   : 'DWI'      ,
    ' DWIProp'           : 'DWI'      ,
    'Ax T2 Flair'        : 'FLax'     ,
    'SAG T1 SE+C'        : 'CET1sag'  ,
    'AXIAL T1 POSTSPECTROSCOPY': 'CET1ax',
    'AXIAL T1 PRE SPECTROSCOPY': 'T1ax',
    'AXIAL T1 PRE-GAD.'  : 'T1ax'     ,
    'AXIAL T1 POST GD THRU TUMOR': 'CET1ax',
    "AX GRE POST SPEC/MODIFY CV'S!": 'NoName',
    'FAST_BRAIN/T1_AXIAL': 'T1ax'     ,
    'FAST_BRAIN/EPIDIFF' : 'DWI'      ,
    'FAST_BRAIN/T1_SAGITTAL': 'T1sag' ,
    'FAST_BRAIN/SCOUT'   : 'localizer',
    'BRAIN_STRYKER/T1_SAG_GAD': 'CET1sag',
    'FLAIR AXIAL'        : 'FLax'     ,
    'ep2d_perf_RELCBF'   : 'rCBF'     ,
    'T1 MPRAGE AX'       : '3dCET1ax' ,
    'T2 AX TSE'          : 'T2ax'     ,
    'T1 FL SAG'          : 'T1sag'    ,
    'ep2d_perf_RELCBV'   : 'rCBV'     ,
    'TRACE ADC_ADC'      : 'ADC'      ,
    'ep2d_perf_RELMTT'   : 'MTT'      ,
    'TRACE ADC'          : 'ADC'      ,
    'T1 FL COR'          : 'T1cor'    ,
    'ep2d_perf_TTP'      : 'TTP'      ,
    'FLAIR_AX'           : 'FLax'     ,
    'T2_AX_TSE_3MM-FS'   : 'T2ax'     ,
    'AXIAL MPGRE'        : '3dT1ax'   ,
    'T1W_3D_stryker'     : '3dT1ax'   ,
    'AX POST'            : 'CET1ax'   ,
    'COR POST'           : 'CET1cor'  ,
    'COR PRE'            : 'T1cor'    ,
    'SAG PRE'            : 'T1sag'    ,
    'SAG POST'           : 'CET1sag'  ,
    'AX PRE'             : 'T1ax'     ,
    'COR T1 SE'          : 'T1cor'    ,
    'COR FSE T2 inter '  : 'T2cor'    ,
    'SAG FSE T2 inter '  : 'T2sag'    ,
    'AX FSE T2 inter'    : 'T2ax'     ,
    'COR T1 SE F + C'    : 'CET1cor'  ,
    'Sag T1 SE F + C'    : 'CET1sag'  ,
    'MPR Stack'          : 'MPR'      ,
    'DTI for NSurg_ADC'  : 'DTI'      ,
    'MRHR T2 AX'         : 'T2ax'     ,
    'MRHR SCOUT'         : 'localizer',
    'MP RAGE AXIAL VOLUMETRIC': '3dT1ax',
    'DTI for NSurg_ColFA': 'FA'       ,
    'DTI for NSurg_FA'   : 'FA'       ,
    'DTI for NSurg'      : 'DTI'      ,
    'AX T1 FLAIR'        : 'T1ax'     ,
    'Diffusion_ADC'      : 'ADC'      ,
    'T1_mprage_Ax Gd'    : 'CET1ax'   ,
    'T1 Se  Cor Gd'      : 'CET1cor'  ,
    'T1_fl2d_Ax  Gd'     : 'T2starax' ,
    'Diffusion_TRACEW'   : 'DWI'      ,
    'T1_tir_axial'       : 'T1ax'     ,
    'T1_fl2d_Sag Gd'     : 'T2starsag',
    'COR T1 POST GD FLAIR': 'CET1scor',
    '*3 PLANE LOC'       : 'localizer',
    '*AXIAL FSE'         : 'NoName'   ,
    '*SAG T1'            : 'T1sag'    ,
    '*AXIAL DTI'         : 'DTI'      ,
    '*COR T1 GD'         : 'CET1cor'  ,
    '*AXIAL PERFUSION'   : 'Perf'     ,
    '*AXIAL T1 GD'       : 'CET1ax'   ,
    '*AXIAL FLAIR'       : 'FLax'     ,
    '*AXIAL T1'          : 'T1ax'     ,
    'C+AX 3D SPGR'       : '3dCET1ax' ,
    'rt cst'             : 'NoName'   ,
    'COR MPR'            : 'MPRcor'   ,
    'SAG MRP'            : 'MPRsag'   ,
    'COR  T1+C'          : 'CET1cor'  ,
    'TSE T2 AXIALS'      : 'T2ax'     ,
    'BrainLab onBL T2axC+': 'T2ax'    ,
    'RA ROUTINE T2 Sag CLEAR': 'T2sag',
    'BrainLab onBL 3DT1axC+': '3dCET1ax',
    'RA ROUTINE DwI best': 'DWI'      ,
    'RA ROUTINE FLAIR AX': 'FLax'     ,
    'RA ROUTINE T2 Sag'  : 'T2sag'    ,
    'RA ROUTINE T1 AX +C': 'CET1ax'   ,
    'RA ROUTINE SENSE SCOUT': 'localizer',
    'RA ROUTINE T2 greAX': 'T2starax' ,
    'RA ROUTINE T1CORSPIR+C': 'CET1fscor',
    'RA ROUTINE T1 AX'   : 'T1ax'     ,
    'RA ROUTINE T2 AX'   : 'T2ax'     ,
    'DTI_15 direction'   : 'DTI'      ,
    '+ C Ax T1 MP SPGR'  : '3dCET1ax' ,
    'Ax PROBE-3DCSI 144TE': 'CSI'     ,
    'VOLUMETRIC AXIAL Gd': '3dCET1ax' ,
    'COR'                : 'cor'      ,
    'SAG'                : 'sag'      ,
    'AX'                 : 'ax'       ,
    'MRHG FLAIR AX'      : 'FLax'     ,
    'MRHG SCOUT'         : 'localizer',
    '8hrbrain,Ax,2D,DWIProp': 'DWI'   ,
    'RT COM CAR'         : 'NoName'   ,
    'MRA BRAIN'          : 'MRA'      ,
    '3D MOTSA'           : 'NoName'   ,
    'LT  COM CAR'        : 'NoName'   ,
    'VERTEBRALS'         : 'NoName'   ,
    'TI AX SE'           : 'T1ax'     ,
    'E_sDW_DIFF'         : 'DWI'      ,
    'DUAL AX SE'         : 'doubleax' ,
    'T2W_FFE'            : 'T2starax' ,
    'T1 AX SE FS POST'   : 'CET1fsax' ,
    'AXIAL flair'        : 'FLax'     ,
    'AXIAL T1 POST GAD.' : 'CET1ax'   ,
    'AXIAL DIFFUSION 1000': 'DWI'     ,
    'AXIAL VARIABLE ECHO PD/T2': 'doubleax',
    'CORONAL T1 POST'    : 'CET1cor'  ,
    'SAGITTAL LOCALIZER' : 'localizer',
    'Ax T1 SE'           : 'T1ax'     ,
    '8hrbrain,Ax,2D,Zoom,DWIProp': 'DWI',
    ' T2Prop'            : 'T2ax'     ,
    'Sag T1 FSE Post Gad': 'CET1sag'  ,
    'Axial T2 FSE Hi-Res': 'T2ax'     ,
    'Axial DWI'          : 'DWI'      ,
    'Sag T1 FSE'         : 'T1sag'    ,
    'Axial T1 FSE Post Gad': 'CET1ax' ,
    'Scanogram SCA'      : 'localizer',
    'Axial T1 FSE'       : 'T1ax'     ,
    'Cor T1 FSE Post Gad': 'CET1cor'  ,
    'Axial FLAIR'        : 'FLax'     ,
    'Axial T2* GE'       : 'T2starax' ,
    'BRAIN_STRYKER/t1_se_cor': 'T1cor',
    'BRAIN_STRYKER/t1_mpr_AX': 'T1mprax',
    'RETRO_ORBIT/T2_LATE_ECHO_B': 'heavyT2',
    'BRAIN_STRYKER/t1_se_tra': 'T1ax' ,
    'BRAIN_STRYKER/t1_sag': 'T1sag'   ,
    'BRAIN_STRYKER/DIFFUSION': 'DWI'  ,
    'BRAIN_STRYKER/t1_se_sag': 'T1sag',
    'COR T1 +C'          : 'CET1cor'  ,
    'Sag T1+C'           : 'CET1sag'  ,
    'SWI_7311'           : 'SWI'      ,
    'SAG T1 FLAIR'       : 'T1sag'    ,
    'BRAIN_NON_CONTRAST/FL_2D_A': 'FLax',
    'ScanningSequence memp': 'T1ax'   ,
    'ScanningSequence fse': 'T2ax'    ,
    'ScanningSequence flair': 'FLax'  ,
    'BRAIN_CONTRAST/svs_se135': 'SVS' ,
    'BRAIN_PITUITARY/PD_T2_AXIA': 'doubleax',
    '(OPT) Ax T2 Flair'  : 'FLax'     ,
    '(OPT) Ax T2 FSE'    : 'T2ax'     ,
    '3D AXIAL,IRSPGR,Fast': '3dT1ax'  ,
    'MRHR T1 AX POST GAD': 'CET1ax'   ,
    'MRHR T1 SAG POST GAD': 'CET1sag' ,
    'MRHR DIFF IPAT'     : 'DWI'      ,
    'MPRAGE SAG  IPAT'   : '3dT1sag'  ,
    'MRHR FLAIR AX'      : 'FLax'     ,
    'MRHR T1 COR POST GAD': 'CET1cor' ,
    'MRHR DIFF IPAT_ADC' : 'DWI'      ,
    'T1 AX'              : 'T1ax'
 }

##############################################

HGGdic = {
    'ASSET PERF'         : 'Perf'     ,
    '3D FSE AX 20 slabs' : 'NoName'   ,
    'FSPGR SAG'          : '3dT1sag'  ,
    '3 PL LOC'           : 'localizer',
    'AX SPGR 3D'         : '3dT1ax'   ,
    'Summary Series'     : 'NoName'   ,
    'AX T1 POST'         : 'CET1ax'   ,
    'Diffusion Weighted' : 'DWI'      ,
    'DTI'                : 'DTI'      ,
    'AX T2 FSE'          : 'T2ax'     ,
    'COR T1 POST'        : 'CET1cor'  ,
    'AX T2*GRE'          : 'T2starax' ,
    'Axial CALIB'        : 'calibration',
    'FIDUCIALS  1.0  SPO  sag': 'NoName',
    'FIDUCIALS  1.0  SPO  cor': 'NoName',
    'Ax FRFSE T2 512 x 512' : 'T2ax'  ,
    'Ax T1 SE POST'      : 'CET1ax'   ,
    'Cor T1 SE POST'     : 'CET1cor'  ,
    'Sag T1 POST'        : 'CET1sag'  ,
    'AX DWI 1000b'       : 'DWI'      ,
    'AX T2FLAIR Prop'    : 'FLax'     ,
    'Sag T1 SE'          : 'T1sag'    ,
    'Ax T1 SE PRE'       : 'T1ax'     ,
    'HEMO'               : 'T2star'   ,
    '           T1 AX PRE' : 'T1ax'   ,
    '           DWI/SSH' :  'DWI'     ,
    '           T1 COR POST' : 'CET1cor',
    '           T2 GRASE': 'T2star'   ,
    '           HEMOSIDERIN' : 'T2star',
    '           T1 SAG'  : 'T1sag'    ,
    '           T1 AX POST' : 'CET1ax',
    '           T1 SAG POST' : 'CET1sag',
    '           FLAIR'   : 'FL'       ,
    'SEIZURE    HEMOSIDERIN' : 'T2star',
    'BRAIN      T1 AX POST' : 'CET1ax',
    'STROKE     FLAIR'   : 'FL'       ,
    'Brain      T1W_SE'  : 'T1'       ,
    'BRAIN      T1 SAG POST' : 'CET1sag',
    'BRAIN      T1 COR POST' : 'CET1cor',
    'SEIZURE    SS DWI'  : 'DWI'      ,
    'SEIZURE    T1 SAG'  : 'T1sag'    ,
    'TBI-FMRI   DTI-SSH' : 'DTI'      ,
    'SEIZURE    T2 GRASE': 'T2star'   ,
    '           T1W 3d'  : '3dT1'     ,
    'PPERFUSION'         : 'Perf'     ,
    '           DW_SSh_b100' : 'DWI'  ,
    '2D WAND T2 WEIGHTED': 'T2'       ,
    '3D WAND T1 WEIGHTED': '3dT1'     ,
    'LOC'                : 'localizer',
    'DIFF 1000 TRY ME 24 FOV' : 'DWI' ,
    '+AxT1-thin for surgery' : 'CET1ax',
    'AxFLAIR-thin for surgery' : 'FLax',
    'SAG FSPGR'          : '3dT1sag'  ,
    'AX 3D FSE'          : '3dax'     ,
    'MRSI -VSS'          : 'MRSI'     ,
    'nordicICE HFH - rBV map -Leakage corrected' : "rCBV" ,
    'nordicICE HFH - rBF map -Leakage corrected' : 'rCBF' ,
    'AX PERFUSION'       : 'Perf'     ,
    'AX 3D SPGR GAD'     : '3dCET1'   ,
    'nordicICE HFH - MTT map -Leakage corrected': 'MTT' ,
    'cor t1+c'           : 'CET1cor'  ,
    'ax diff'            : 'DWI'      ,
    'ax t1+c'            : 'CET1ax'   ,
    'sag t1+c'           : 'CET1sag'  ,
    'ax t1'              : 'T1ax',
    'ax t2' :              'T2ax',
    'COR T1 GD' :          'CET1cor',
    'CORONAL  T1 GD' : 'CET1cor',
    'Apparent Diffusion Coefficien' : 'ADC',
    '' : 'NoName',
    'BRAIN WO/W COR T1 POST' : 'CET1cor',
    'BRAIN WO/W FLAIR AX' : 'FLax',
    'BRAIN WO/W AX T1 POST' : 'CET1ax',
    'BRAIN WO/W SS DIFF' : 'DWI',
    'BRAIN WO/W SURVEY/MST' : 'localizer',
    'BRAIN WO/W T2 GRASE AX' : 'T2ax',
    'STROKE     VEN/3D/PCA' : 'PC-MRA',
    'BRAIN WO/W AX T1 PRE' : 'T1ax',
    'BRAIN WO/W T1 SAG' : 'T1sag',
    'STROKE     MIP VEN/3D/P' : 'MRA',
    'Recon 2:' : 'NoName',
    'brain with SS DWI' : 'DWI',
    'brain with T2 AX GRASE' : 'T2ax',
    'brain with T1 SAG 23SL' : 'T1sag',
    'brain with mst scout' : 'localizer',
    'brain with Ax T1 Pre' : 'T1ax',
    'brain with Cor T1 Post' : 'CET1cor',
    'brain with FLAIR' : 'FLax',
    'brain with AX T1 POST' : 'CET1ax',
    'BRAIN W/WO FLAIR AX' : 'FLax',
    'BRAIN W/WO T2 AX GRASE' : 'T2ax',
    'BRAIN W/WO T1 COR POST' : 'CET1cor',
    'BRAIN W/WO T1 AX POST' : 'CET1ax',
    'BRAIN W/WO T1 SAG 23SL' : 'T1sag',
    'BRAIN W/WO T1 AX PRE' : 'T1ax',
    'BRAIN W/WO mst scout' : 'localizer',
    '100CCOMNI HAND INJECT' : 'NoName',
    'stealth/vecstealth' : 'NoName',
    'PHOTON     GADO T1' : 'CET1',
    'PHOTON     T1 HEADFRAME' : 'T1',
    '+COR T1' : 'T1cor',
    'Axial ssfse' : 'SST2ax',
    'MRI BRAIN Sag T1 SE' : 'T1sag',
    'brain w/o & with sag t1' : 'T1sag',
    't2_ax hemo_FIL' : 'T2starax',
    'perfusion_TTP' : 'TTP',
    'T2_AX_TSE_FS_512' : 'T2fsax',
    't1_tra pre_FIL' : 'T1ax',
    't1_cor post_FIL' : 'CET1cor',
    't2_flair ax' : 'FLax',
    'ep2d_diff_3scan_ADC' : 'ADC',
    'ep2d_diff_3scan' : 'DWI',
    't1_tra post_FIL' : 'CET1ax',
    'T1 sag post' : 'CET1sag',
    'MRI BRAIN sag t1' : 'T1sag',
    't1_tra pre' : 'T1ax',
    't2_ax hemo' : 'T2star',
    'T2_AX_FS post' : 'T2fsax',
    't1_sag' : 'T1sag',
    't1_cor post' : 'CET1cor',
    't1_tra post' : 'CET1ax',
    'BRAIN WO/W HEMOSIDERIN' : 'T2starax',
    '3DSPGR AXIAL' : '3dT1ax',
    'FMPSPGR SAG' : '3dT1sag',
    'AD' : 'NoName',
    '3DFSE AXIAL' : '3dNoName',
    'Brain      T1 COR POST  COR    SE    507       12     90' : 'CET1cor',
    'Brain      mst scout    MST    T1FFE 19        9.2    60' : 'localizer',
    'Brain      TUMOR ANALYS TRA    SE    650       15     90' : 'T1ax',
    'Brain      T1 AX POST   TRA    SE    507       12     90' : 'CET1ax',
    'Brain      EASY GUIDE   TRA    T1FFE 30        4.5    30' : 'localizer',
    'Brain      T2 AX GRASE  TRA    GraSE 5000      100    90' : 'T2ax',
    'Brain      T1 SAG 23SL  SAG    SE    568       14     90' : 'T1sag',
    'Brain      FLAIR AX     TRA    TIR   11000     120    90' : 'FLax',
    'Brain      T1 AX PRE    TRA    SE    500       11     90' : 'T1ax',
    'STROKE     PREST/PERF   TRA    FEEPI 18        26     8' : 'T2star',
    'MOTOR' : 'Function',
    'WORDGEN RIGHT COR' : 'Function',
    'RECEP LEFT COR' : 'Function',
    'RECEP LEFT SAG' : 'Function',
    't1_se_tra' : 'T1ax',
    'MOTOR SAG RIGHT' : 'Function',
    'MOTOR 2' : 'Function',
    'RECEP RIGHT AX' : 'Function',
    'Mean_&_t-Maps' : 'Function',
    'RECEP LEFT AX' : 'Function',
    'WORDGEN LEFT SAG' : 'Function',
    'gre_field_mapping' : 'B1mapping',
    'act_MoCoSeries' : 'Function',
    'EvaSeries_tTest' : 'Function',
    'MOTOR SAG LEFT' : 'Function',
    'WORDGEN RT AX' : 'Function',
    'MOTOR SAG LT' : 'Function',
    'WORDGEN RT SAG' : 'Function',
    'MOTOR COR' : 'Function',
    'WORDGEN LEFT COR' : 'Function',
    'RECEP RIGHT COR' : 'Function',
    'WORDGEN' : 'Function',
    'RECEP RIGHT SAG' : 'Function',
    'WORDGEN LEFT AX' : 'Function',
    'Reformatted' : 'MPR',
    'ax 3d fspgr +c' : '3dCET1ax',
    'Recon 2: Routine Head' : 'MPR',
    'Routine Head' : 'localizer',
    'Scout' : 'localizer',
    'brain with DWI/SSH' : 'DWI',
    'brain with T2 Hemosidr' : 'T2star',
    'brain with T1 SAG post' : 'CET1sag',
    'STEALTH/VECT1W 3d' : 'NoName',
    'SAG. T1' : 'T1sag',
    'CORONAL T1   POST GAD' : 'CET1cor',
    'AXIAL T1   POST GAD' : 'CET1ax',
    '3D SPGR AX' : '3dT1ax',
    'AX FLAIR gad' : 'CEFLax',
    'Combined Image' : 'Fusion',
    '3D FSE AX' : '3dFSEax',
    'T2 quantitation' : 'T2map',
    'Attenuation Coefficient Map' : 'B1mapping',
    'Negative Enhancement Integral' : 'NoName',
    'single_expo t2 (ms)' : 'NoName',
    'PERFUSION 15 sec inject.delay' : 'Perf',
    'Recon 3: HEAD ROUTINE' : 'NoName',
    'HEAD ROUTINE' : 'NoName',
    'Recon 2: HEAD ROUTINE' : 'NoName',
    'SCOUT AP/LAT' : 'localizer',
    'HEAD WO' : 'localizer',
    'Recon 2: HEAD WO' : 'NoName',
    'Recon 2: HEAD WITH' : 'NoName',
    'HEAD WITH' : 'NoName',
    'NoName' : 'NoName',
    'SC:COPLANAR PD/T2 FSE ASSET' : 'doubleax',
    'SC:HIGH RES T1 ASSET 3D FSPGR' : '3dT1ax',
    '+C T1 AX' : 'CET1ax',
    'MRHG T1 AX' : 'T1ax',
    'MRHG DIFF' : 'DWI',
    'MRHG T1 AX POST GAD' : 'CET1ax',
    'MRHG T1 SAG POST GAD' : 'CET1sag',
    'MRHG T1 COR POST GAD' : 'CET1cor',
    'MRHG DIFF_ADC' : 'DWI',
    'ax t1 +c' : 'CET1ax',
    'ax pd' : 'PDac',
    'cor mprage +c' : '3dCET1cor',
    'ax flair' : 'FLax',
    'SAG REFORMAT' : 'MPRsag',
    'sag t1 +c' : 'CET1sag',
    'ax diff_ADC' : 'DWI',
    'COR REFORMAT' : 'MPRcor',
    'Ax DWI 1000b ASSET' : 'DWI',
    'ASSET Cal' : 'calibration',
    '3D FSE AXIAL' : '3dax',
    '3d T1 FSPGR  CONT' :'3dCET1ax',
    'Ax T2 FLAIR' : 'FLax',
    'PURE: body coil cal' : 'calibration',
    'PURE: surface coil cal' : 'calibration',
    'PERFUSION  15 sec inject dela' : 'Perf',
    'AX T1 PRE GD FLAIR' : 'T1ax',
    'AXIAL LOC' : 'localizer',
    'AXIAL gad' : 'CET1ax',
    'Exponential Apparent Diffusio' : 'expADC',
    'cor t1 +c' : 'CET1cor',
    'sag t2' : 'T2sag',
    'ax t2+c' : 'CET2ax',
    'STROKE     MIP 3D VB IN' : 'MIP',
    'STROKE     SURVEY/MST' : 'localizer',
    'STROKE     T2 GRASE AX' : 'T2ax',
    'STROKE     MIP M2D CARO' : 'MIP',
    'STROKE     FLAIR AX' : 'FLax',
    'STROKE     T1 SAG' : 'T1sag',
    'STROKE     M2D CAROTID' : 'plaque',
    'STROKE     3D VB INFLOW' : 'MRA',
    'BRAIN WO/W AX T1' : 'T1ax',
    'STEALTH/VECBRAIN LAB' : 'NoName',
    'STEALTH/VECmst scout' : 'localizer',
    'ax spgr t1 +c' : '3dCET1ax',
    '3-PLANE LOC' : 'localizer',
    'EPI-SE CBV-PERM' : 'rCBV',
    'FLAIR CORONAL' : 'FLcor',
    'Head,Ax,Spectro,Spin Echo,EDR' : 'MRS',
    'BRAIN W/WO COR POST' : 'CET1cor',
    'BRAIN W/WO T1 PRE' : 'T1ax',
    'BRAIN W/WO SS DWI_' : 'DWI',
    'BRAIN W/WO FLAIR' : 'FLax',
    'FAST BRAIN t-1 SAG GAD' : 'CET1sag',
    'BRAIN W/WO T2 HEMOSID' : 'T2starax',
    'BRAIN W/WO DTI/medium' : 'DTI',
    'BRAIN W/WO T1 POST' : 'CET1ax',
    'BRAIN W/WO T1 SAG' : 'T1sag',
    'BRAIN W/WO T2 GRASE' : 'T2ax',
    'PERFUSION' : 'Perf',
    'AXIAL PD/T2 FSE' : 'doubleax',
    'AXIAL PERFUSION POST GD' : 'Perf',
    'MRI BRAIN sag t1_S2_DIS2D' : 'T1sag',
    'ep2d_diff0_1000' : 'DWI',
    'T2_AX_FS' : 'T2fs',
    'ep2d_diff0_1000_ADC' : 'ADC',
    'RAPID BRAIN*FLAIR AX' : 'FLax',
    'BRAIN W/WO *T1 SE SAG' : 'T1sag',
    'RAPID BRAIN*T1 SE AX+' : 'CET1ax',
    'BRAIN W/WO *T1 SE AX' : 'T1ax',
    'BRAIN W/WO *T1 SE COR+C' : 'CET1cor',
    'RAPID BRAIN*T2 TSE AX' : 'T2ax',
    'BRAIN W/WO *DW SSh AX' : 'DWI',
    't2_flair cor' : 'FLcor',
    't2_flair sag' : 'FLsag',
    'Ax T1 SE ' : 'T1ax',
    't1_tra' : 'T1ax',
    'brain wo sag t1' : 'T1sag',
    'FLAIR' : 'FL',
    'T2 AX FS' : 'T2fsax',
    'HEMOSIDERIN' : 'T2star',
    'T1 sag post_FIL' : 'CET1sag',
    'MR BRAIN SAG T1' : 'T1sag',
    '           SS DWI' : 'DWI',
    '           T1 SAG 23SL' : 'T1sag',
    'TSE T2' : 'T2',
    'DIFF EPI ADC' : 'DWI',
    'SAG SE T1FS POST' : 'CET1fssag',
    'SAG TSE3D T2' : '3dT2sag',
    'ax mpr' : 'MPRax',
    'sag mpr' : 'MPRsag',
    'T1 POST GD' : 'CET1',
    'COR SE T1 POST' : 'CET1cor',
    'LOCALIZER IN PLANE CSI' : 'localizer',
    'GRE T2' : 'T2star',
    'SAG SE T1' : 'T1sag',
    'DIFF EPI' : 'DWI',
    'AX SE T1' : 'T1ax',
    'cor mpr' : 'MPRcor',
    'LOCALIZER' : 'localizer',
    'EP2D BLK.BLOOD' : 'NoName',
    'ax flair+c' : 'CEFLax',
    'TENSOR EPI ASSET' : 'DTI',
    '3PL LOC' : 'localizer',
    'se epi' : 'DWI',
    'ax tensor' : 'DTI',
    'ax t2 +c' : 'CET2ax',
    'T1_AX' : 'T1ax',
    'T2_AX' : 'T2ax',
    'GRADIENT' : 'T2star',
    'T1_COR_gado' : 'CET1cor',
    'T1_AX_gado' : 'CET1ax',
    'DCE DYNAMIC' : 'DCE',
    'DCE T1 MAPPING' : 'T1mapping',
    'T2 wand' : 'T2',
    'FSE T2' : 'T2',
    'ASSET Calib' : 'calibration',
    'COR 3D POST' : '3dCET1cor',
    'SE SAG T1 POST' : 'CET1sag',
    'SE T1' : 'T1ax',
    'AXIAL T1 +C' : 'CET1ax',
    'DTI N=27' : 'DTI',
    'FSPGR 3D' : '3dT1',
    '3-P Loc' : 'localizer',
    'AX DWI' : 'DWI',
    'Axial T2*' : 'T2starax',
    'T2 FLAIR' : 'FLax',
    'Mean Time to Enhance' : 'TTP',
    'T1 COR POST GAD' : 'CET1cor',
    'T1 AX POST GAD' : 'CET1ax',
    '3D MRS PROBE P' : 'MRS',
    'COR FLAIR' : 'FLcor',
    'AXIAL T2/PD' : 'doubleax',
    'AX T1+C' : 'CET1ax',
    'AX GRE' : 'T2starax',
    'TSE T2 SAG' : 'T2sag',
    'BRAIN      FLAIR' : 'FLax',
    'BRAIN      T1 AX PRE' : 'T1ax',
    'BRAIN      HEMOSIDERIN' : 'T2starax',
    'BRAIN      SS DWI' : 'DWI',
    'BRAIN      T2 GRASE' : 'T2ax',
    'BRAIN      T1 SAG' : 'T1sag',
    'brain with sag post' : 'CET1sag',
    '           SS DWI_ SEN' : 'DWI',
    '           FLAIR SENSE' : 'FLax',
    '           T1 AX PRE C' : 'T1ax',
    '           T2 GRASE SE' : 'T2ax',
    '           POST COR CL' : 'CET1cor',
    '           T2 HEMOSID' : 'T2star',
    '           SAG POST CL' : 'CET1sag',
    '           SAG CLEAR' : 'NoNamesag',
    'quick brainT2/FLAIR' : 'FLax',
    'quick brainT1 SAG FFE' : 'T1sag',
    'quick brainT1 AX FFE' : 'T1ax',
    'quick brainHEMOSIDERN' : 'T2starax',
    'quick brainT2W/TSE/SSh' : 'T2ax',
    'quick brainAx T1 Post' : 'CET1ax',
    'quick brainCOR GADO' : 'CET1cor',
    'quick brainAx T1 Pre' : 'T1ax',
    'STEALTH/VECT1W/3D/FFE' : '3dT1ax',
    't1_3D FFE STEALTH' : '3dT1ax',
    'COR T1 FLAIR C+' : 'CET1cor',
    'Sag T1 FLAIR' : 'T1sag',
    'AX T1 FLAIR C+' : 'CET1ax',
    '3PLANE PERFORM' : 'localizer',
    'Ax DWI' : 'DWI',
    'Apparent Diffusion Coefficient (mm²/s)' : 'ADC',
    'AX T2 FLAIR PROPELLER' : 'FLax',
    'Ax T2 PROPELLER' : 'T2ax',
    'TOF 3 SLAB' : 'MRA',
    'PJN' : 'MRA',
    'ep2d_diffusion_ADC' : 'ADC',
    'ep2d_diffusion' : 'DWI',
    't2_ax' : 'T2ax',
    'AX DTI - TENSOR' : 'DTIax',
    'DIR DIFF' : 'DIR',
    'VSS MRSI' : 'CSI',
    'PERMEABILITY DYNAMIC' : 'DCE',
    'AX T2 POST' : 'CET2ax',
    'Ax T1 POST' : 'CET1ax',
    'Sag T1' : 'T1sag',
    'SAG MPRAGE POST' : '3dCET1sag',
    'AX T2 GRE' : 'T2starax',
    'sag' : 'sag',
    'AX T1 MPRAGE POST' : '3dCET1ax',
    'AX DWI_ADC' : 'DWI',
    'AX T1 Pre' : 'T1ax',
    'cor' : 'cor',
    'AX T2 FS Post' : 'T2fsax',
    'AX T1 Post' : 'CET1ax',
    'SAG MP-RAGE' : '3dT1sag',
    'COR RECON POST' : 'CEMPRcor',
    'AX T2 GRE_FIL' : 'T2starax',
    'SAGT1 POST' : 'CET1sag',
    'AX T1 Post_FIL' : 'CET1ax',
    'AX T2 FS' : 'T2fsax',
    'SAG 3D DIX Post_in' : '3dCET1sag',
    'CORONAL MPR' : 'MPRcor',
    'SAG 3D DIX Post_W' : '3dCET1sag',
    'SAG 3D DIX Post_opp' : '3dCET1sag',
    'SAG MP-RAGE Post' : '3dCET1sag',
    'AX DWI (WIP)_ADC' : 'ADC',
    'AX DWI (WIP)' : 'DWI',
    'Stealth' : 'NoName',
    't1_ax post' : 'CET1ax',
    'mri brain t1_sag mp rage' : '3dT1sag',
    'dwi ax' : 'DWI',
    't1_sag mp rage post' : '3dCET1sag',
    't2_fs ax' : 'T2fsax',
    't1_ax pre' : 'T1ax',
    'dwi ax_ADC' : 'ADC',
    't2_hemo ax' : 'T2starax',
    'ep2d_perf' : 'Perf',
    '3-PL LOC' : 'localizer',
    'COR POST MPR' : 'CEMPRcor',
    'FSE Tractography Stealth' : 'DTI',
    'DTI Tractography' : 'DTI',
    'SPGR Tractography Stealth' : 'DTI',
    'axial si' : 'ax',
    'flair' : 'FL',
    'per' : 'Perf',
    't1_se_sag' : 'T1sag',
    't2_fl2d_tra_hemo' : 'T2starax',
    't2_flair_tra_dark-fluid' : 'FLax',
    't2_tse_tra_512' : 'T2ax',
    't1_se_sag post' : 'CET1sag',
    'DTI 3.2mm WH' : 'DTI',
    '2-3D DCE T1 MAP' : 'DCE',
    'dDIFFUSION SENSE' : 'DWI',
    'T1 AX PRE' : 'T1ax',
    'T1 COR.  POST' : 'CET1cor',
    'eB800' : 'NoName',
    'AX. FLAIR' : 'FLax',
    'T1 AX POST' : 'CET1ax',
    'eB0' : 'DWIb0',
    'ax spgr +c' : '3dCET1ax',
    'COR DUAL' : 'doublecor',
    'Ax T2Flair' : 'FLax',
    'Ax T2' : 'T2ax',
    '3 pl LOC' : 'localizer',
    'epiRT - PCOMP' : 'NoName',
    '3-P Localizer' : 'localizer',
    '3D Volume' : '3d',
    'epiRT - LHAND' : 'Function',
    'epiRT - RHAND' : 'Function',
    'epiRT - CAT' : 'Function',
    'Anatomy' : '3dT1',
    'fMRI - CAT' : 'Function',
    'Cor SE T1' : 'T1cor',
    'DWI' : 'DWI',
    'fMRI - PCOMP' : 'Function',
    'Sag SE T1' : 'T1sag',
    'Ax SE T1 Post' : 'CET1ax',
    'fMRI - FAS' : 'Function',
    'T2 FLAIR 2 MM' : 'FLax',
    'GROSS SZ   AXIAL IR 2MM' : 'T1ax',
    'GROSS SZ   T1W 3d' : '3dT1ax',
    'Recon 2: ' : 'NoName',
    'BRAIN WO/W tumor volume' : '3dT1',
    'BRAIN W/WO TUMOR VOLUME' : '3dT1',
    'BRAIN W/WO T1 AX Post' : '3dCET1ax',
    'BRAIN W/WO' : 'NoName',
    'mra abd' : 'MRA',
    'BRAIN W/WO SS DWI' : 'DWI',
    'SYRYKER    mst scout' : 'localizer',
    'SYRYKER    STRYKER' : 'NoName',
    'brain with TUMOR VOLUME' : 'NoName',
    'STAND BRAIN*AXIAL FLAIR' : 'FLax',
    'STEALTH    *perm dyn3D' : 'DCE',
    'STEALTH    *T1/FFE/SAG' : 'T1sag',
    'STEALTH    *3DT1/STEALT' : '3dT1',
    'STEALTH    survey/MST' : 'localizer',
    'STEALTH    *3DT2/STEALT' : '3dT2',
    'fMRI - RHand' : 'Function',
    'fMRI - LHand' : 'Function',
    'fMRI - BOTH HANDS' : 'Function',
    'fMRI Anat' : 'Function',
    't2_flair COR' : 'FLcor',
    'T2_AX_TSE_FS' : 'T2fsax',
    'tumor volumeGADO' : '3dCET1ax',
    'tumor volume pre' : '3dT1ax',
    'T2_AX_TSE_FS_post' : 'T2fsax',
    't1_fl2d cor' : 'T1cor',
    't2_blade_tra' : 'T2ax',
    't1_fl2d ax' : 'T1ax',
    'perfusion' : 'Perf',
    'repeat t2_flair ax' : 'FLax',
    'COR T2 FLAIR' : 'FLcor',
    'Ax T2 POST' : 'T2ax',
    'Ax T1 PRE' : 'T1ax',
    'ToF-2D' : 'MRA',
    'LEFT CAROTID' : 'carotid',
    'RIGHT CORTOID' : 'carotid',
    'RIGHT CAROTID' : 'carotid',
    'AX 3D T1 MPRAGE ipat' : '3dT1ax',
    'ToF-3D-COW_MIP_TRA' : 'MRA',
    'COW NOD' : 'NoName',
    'ANT CIRC NOD' : 'NoName',
    'RIGHT CIRC SPIN' : 'NoName',
    'ToF-3D-COW_MIP_COR' : 'MRA',
    'LEFT CIRC SPIN' : 'NoName',
    'ToF-3D-COW' : 'MRA',
    'AX MPR' : 'MPRax',
    'T1 3D FFE' : '3dT1ax',
    'AX FLAIR ' : 'FLax',
    'Ax 3D FSPGR Asset' : '3dT1ax',
    'AXIAL T1   POST GAD  #2' : 'CET1ax',
    'CORONAL T1    POST GAD' : 'CET1cor',
    'AXIAL T1    POST  GAD' : 'CET1ax',
    'VI Snapshot (0)' : 'NoName',
    'brain with TUMOR-PERFUS' : 'NoName',
    'VI Snapshot (16)' : 'NoName',
    'brain with T1 SAG POST' : 'CET1sag',
    'TUMOR VOLUME PRE' : '3dT1ax',
    '3-pl Loc' : 'localizer',
    'TUMOR VOLUME POST' : '3dCET1ax',
    'Calibration Scan' : 'calibration',
    'NABITT     T1 SAG 23SL' : 'T1sag',
    'NABITT     T1 PRE' : 'T1ax',
    'NABITT     AX T1 POST' : 'CET1ax',
    'NABITT     Cor T1 Post' : 'CET1cor',
    'NABITT     FLAIR' : 'FLax',
    'NABITT     T2 AX GRASE' : 'T2ax',
    'Time to Minimum' : 'NoName',
    'MRHR GE AX' : 'NoName',
    'Ax DTI B 1000' : 'DWI',
    'AX T1 pre GD FLAIR' : 'T1ax',
    'AX T2 FR-FSE' : 'T2ax',
    'ax t1POST' : 'CET1ax',
    'QUICK HEADS3 WAY SCOUT  MST    T1TFE 11        5      35' : 'localizer',
    'QUICK HEADST1 AX pre    TRA    SE    500       15     90' : 'T1ax',
    'QUICK HEADST1 cor post  COR    SE    500       15     90' : 'CET1cor',
    'QUICK HEADST1 AX POST   TRA    SE    450       15     90' : 'CET1ax',
    "QUICK HEADST2 TSE AX'   TRA    TSE   3500      120    90" : 'T2ax',
    'QUICK HEADSmets sag     SAG    SE    600       18     90' : 'CET1sag',
    "QUICK HEADSFLAIR'       TRA    IRTSE 8000      120" : 'FLax',
    'Brain      *easy guide  TRA    FFE   30        5      30' : 'localizer',
    'Brain      3 WAY SCOUT  MST    T1TFE 11        5      35' : 'localizer',
    'volumetric' : '3dT1ax',
    'T2 AX 2mm' : 'T2ax',
    'DTI 1000 24 FOV' : 'DTI',
    'GD AX T1' : 'CET1ax',
    'PRE AX T1' : 'T1ax',
    'GD COR T1' : 'CET1cor',
    '3D IRSPGR' : '3dT1ax',
    'Axial ssflair' : 'FLax',
    'COR T1GD' : 'CET1cor',
    '3-pl T2* FGRE' : 'localizer',
    '3D SPGR POST GD' : '3dCET1ax',
    'DIFFUSION 1000' : 'DWI',
    '3D SPGR PRE GD' : '3dCET1ax',
    '3D T1 MAPPING' : '3dT1ax',
    '3D DCE DYNAMIC' : 'DCE',
    'Ax  DW-EPI' : 'DWI',
    'Sag T1 FSE S' : 'T1sag',
    'COR T1 FSE +C' : 'CET1cor',
    'AX T1 FSE H+C' : 'CET1ax',
    'T1 SE SAG' : 'T1sag',
    'T2 TSE AX' : 'T2ax',
    'AXIAL T1 SI LOC' : 'T1ax',
    'DCE MAP 10FLIP' : 'DCE',
    'ASSET calibration' : 'calibration',
    'DCE MAP 25FLIP' : 'T1mapping',
    'DCE MAP 15FLIP' : 'T1mapping',
    'DCE MAP 5FLIP' : 'T1mapping',
    'DTI 2.6mm' : 'DTI',
    '3Plane Loc SSFSE' : 'localizer',
    'DCE MAP 2FLIP' : 'T1mapping',
    'DCE MAP 20FLIP' : 'T1mapping',
    'Dynamic Susceptibility Imaging' : 'Perf',
    'DTI 6 dir ASSET' : 'DTI',
    'epiRT - FAS' : 'NoName',
    'axial T1 SI Localizer' : 'localizer',
    'AXIAL DIFF' : 'DWI',
    'AXIAL T1 POST' : 'CET1ax',
    'AXIAL T1 PRE' : 'T1ax',
    'FSE AX !MR BRAIN!' : 'NoNameax',
    'TI SAG !MR BRAIN! WHOLE HEAD' : 'T1sag',
    'ep2d_diff_mddw_20_p2' : 'DWI',
    'Design' : 'NoName',
    'ep2d_diff_mddw_20_p2_ADC' : 'DWI',
    'intermediate t-Map' : 'NoName',
    'ep2d_pace_dynt_moco RECEP' : 'Function',
    '<WORD GEN COR[1]>' : 'Function',
    'StartFMRI' : 'Function',
    'ep2d_ MOTOR 2' : 'Function',
    'EvaSeries_GLM' : 'Function',
    '<WORD GEN SAG RIGHT[1]>' : 'Function',
    'MOTOR AX' : 'Function',
    '<WORDGEN SAG LEFT[1]>' : 'Function',
    '<RECEPTIVE AX[1]>' : 'Function',
    'CORONAL flair' : 'FLcor',
    'AXIAL T1 SI GAD' : 'CET1ax',
    'nordicIce HFH - MTT map -Leakage corrected' : 'MTT',
    'nordicIce HFH - rBV map -Leakage corrected' : 'rCBV',
    'nordicIce HFH - rBF map -Leakage corrected' : 'rCBF',
    'Screen Save' : 'ScreenSave',
    'Histogram Image' : 'ScreenSave',
    'Lactate/Lipid nCr' : 'MRS',
    'Creatine Sm,nCr' : 'MRS',
    'Creatine nCr' : 'MRS',
    'Choline Sm,nCr' : 'MRS',
    'NAA Sm,nCr' : 'MRS',
    'Lactate/Lipid Sm,nCr' :  'MRS',
    'Lipid Sm,nCr' : 'MRS',
    'Choline nCr' : 'MRS',
    'NAA nCr' : 'MRS',
    'Lipid nCr' : 'MRS',
    'AX T1 pre si' : 'T1ax',
    'AX T1post gd  si' : 'CET1ax',
    'AXIAL SI LOCAL' : 'localizer',
    'GAD AX T1' : 'CET1ax',
    'Average DC4 FOV 6 DIRECTIONS' : 'ADC',
    'DTI 1000 24 FOV 6 DIRECTIONS' : 'DTI',
    'Fractional Ansio. DIRECTIONS' : 'FA',
    'T2-weighted trace DIRECTIONS' : 'DWIT2wtrace',
    'Ax FSE PD' : 'PDax',
    'Ax FSE T2' : 'T2ax',
    '*GAD AX T1' : 'CET1ax',
    'Average DC24 FOV 6 DIRECTIONS' : 'ADC',
    '*PRE AX T1' : 'T1ax',
    'Fractional Ansio.6 DIRECTIONS' : 'FA',
    '*DTI 1000 24 FOV 6 DIRECTIONS' : 'DTI',
    'T2-weighted trace6 DIRECTIONS' : 'DWIT2wtrace',
    '*AX T2 FLAIR' : 'FLax',
    '*GAD COR T1' : 'CET1cor',
    '*Ax T2 FSE' : 'T1ax',
    '*3 PLANE' : 'localizer',
    'ax tse t1 +c' : 'CET1ax',
    'POST COR  T1' : 'CET1cor',
    'POST AX T1' : 'CET1ax',
    'Diffusion Coefficient' : 'ADC',
    'COR.  FLAIR' : 'FLcor',
    'Probe-P' : 'MRS',
    'probeSI' : 'MRS',
    'T2 FLAIR-2MM' : 'FLax',
    'POST-Sag SE T1' : 'CET1sag',
    'POST-Cor SE T1' : 'CET1cor',
    'QUICK HEADSFLAIR AX     TRA    TIR   11000     120    90' : 'T1ax',
    'QUICK HEADST1 AX PRE    TRA    SE    622       15     90' : 'T1ax',
    'QUICK HEADSmst scout    MST    T1FFE 19        9.2    60' : 'localizer',
    'QUICK HEADST1 SAG 23SL  SAG    SE    622       15     90' : 'T1sag',
    'QUICK HEADST2 AX GRASE  TRA    TSE   5000      100    90' : 'T2ax',
    'QUICK HEADST1 cor POST  COR    SE    500       15     90' : 'CET1cor',
    'QUICK HEADST1 AXIAL     TRA    SE    500       15     90' : 'T1ax',
    'QUICK HEADST1 AX POST   TRA    SE    500       15     90' : 'CET1ax',
    'ADC Slope' : 'ADC',
    'T1 AXIAL' : 'T1ax',
    'T2 TSE AXIAL' : 'T2ax',
    'T2 TSE COR' : 'T2cor',
    'T1 AXIAL  POST' : 'CET1ax',
    'ADC' : 'ADC',
    'T1 COR +C' : 'CET1cor',
    'ep2d_diff_orth_basic PAT2' : 'DWI',
    'ax t1 +c 1.5mm' : '3dCET1ax',
    'FL:C/AXIAL FSE' : 'CET1ax',
    'AX T1 POST gd' : 'CET1ax',
    'POST 3D IRSPGR' : '3dCET1ax',
    'GD AxT1-thin for surgery' : 'CET1ax',
    'Brain      T1 AX PRE    TRA    SE    627       15     90' : 'T1ax',
    'Brain      T1 AX POST   TRA    SE    627       15     90' : 'CET1ax',
    'Brain      T1 COR POST  COR    SE    450       15     90' : 'CET1cor',
    'QUICK HEADSSAG SCOUT    SAG    SE    600       18     90' : 'localizer',
    'Smart Prep Series' : 'NoName',
    'PE' : 'NoName',
    'FSPGR 3D 25FOV' : '3dT1ax',
    'T2 FLAIR2MM25FOV' : 'FLax',
    'SE COR T1 POST' : 'CET1cor',
    '3D AX FSPGR POST' : '3dCET1ax',
    'Seg Structural' : '3dT1',
    'SAG T1 SE CLEAR' : 'T1sag',
    'eB1000' : 'DWI',
    'Survey_SHC' : 'localizer',
    'PRE AX T1 CLEAR' : 'T1ax',
    'AX T2 TSE SENSE' : 'T2ax',
    'POST COR T1 CLEAR' : 'CET1cor',
    'MSh_PERF AX CLEAR' : 'Perf',
    'AX FLAIR  CLEAR' : 'FLax',
    'DW_SSh 160 SENSE' : 'DWI',
    'POST AX T1 CLEAR' : 'CET1ax',
    'STEALTH/VECBRAIN LAB*' : 'localizer',
    'PRE 3D IRSPGR' : '3dT1ax',
    'nordicIce UCSF - rBF map -Leakage corrected' : 'rCBF',
    'Maximum Slope of Increase' : 'MaxSlope',
    'nordicIce UCSF - rBV map -Leakage corrected' : 'rCBV',
    'nordicIce UCSF - MTT map -Leakage corrected' : 'MTT',
    'Maximum Slope of Decrease' : 'MaxSlope',
    'Head,Sag,2D,Spin Echo,NPW' : 'NoName',
    'AXIAL T1 PRE/GD' : 'T1ax',
    'AXIAL PER' : 'Perf',
    'SAGITTAL T1' : 'T1sag',
    'DTI-TRACTOGRAPHY' : 'DTI'
 }

BTdic = LGGdic.update(HGGdic)
